version: "3"
services:
  spring-app:
    build: ./
    ports:
      - "8080:8080"
    env_file: .env
    links:
      -   "redis:redis"
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
  redis-insight:
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    links:
      - "redis:redis"